// The site is FINDABLE — the part that was quietly missing.
//
// Forty category pages were built so Arabic searches for a category name could
// reach the game, and every one of them carried `noindex,nofollow` from the day
// it was generated. So did the landing page, which meant `nofollow` would have
// stopped anything reaching them even if they had been indexable themselves.
// The whole thing was invisible to search engines while looking finished.
//
// ⚠️ AND THE URLS MOVED FIRST, on purpose. They were `/preview/c/<id>.html`.
// "preview" reads as unfinished in a search result, and an address is permanent
// in practice — once Google has learned one, changing it forfeits whatever
// ranking it built. The rename was free the day before indexing and expensive
// the day after, so it happened first.
//
// This file pins the three things that make the difference, each of which fails
// silently: the meta tag, the sitemap being complete and in step, and the old
// addresses still resolving.
import { readFileSync, existsSync, readdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const checks = [];
const check = (n, ok, extra) => {
  checks.push(!!ok);
  console.log(`${ok ? "PASS" : "FAIL"}  ${n}${extra ? "  — " + extra : ""}`);
};
const read = f => (existsSync(join(ROOT, f)) ? readFileSync(join(ROOT, f), "utf8") : "");

const landing = read("about/index.html");
const sitemap = read("sitemap.xml");
const robots = read("robots.txt");

/* ── the landing page invites indexing ──────────────────────────── */
check("the landing page exists at /about/", landing.length > 1000);
/* ⚠️ Both halves matter and they fail differently. `noindex` hides the page;
   `nofollow` hides everything it links to — which is all forty category
   pages. */
check("…and is not noindex", !/content="[^"]*noindex/.test(landing));
check("…nor nofollow, which would strip the category pages of every inbound link",
  !/content="[^"]*nofollow/.test(landing));
check("…and names its own canonical",
  /<link rel="canonical" href="https:\/\/izzbah\.com\/about\/">/.test(landing));

/* ── every category page, likewise ──────────────────────────────── */
const pages = existsSync(join(ROOT, "c"))
  ? readdirSync(join(ROOT, "c")).filter(f => f.endsWith(".html")) : [];
check(`the category pages live at /c/ (${pages.length} of them)`, pages.length >= 30,
  `${pages.length} pages`);
const bad = pages.filter(f => /content="[^"]*noindex/.test(read("c/" + f)));
check("…and none is noindex", bad.length === 0, bad.slice(0, 3).join(", "));
/* ⚠️ A canonical per page, pointing at ITSELF at the new address. A page
   canonicalising to the old /preview/ path would hand Google an address that is
   now a redirect stub — the exact "Duplicate, Google chose different canonical"
   report the root move was made to clear. */
const wrongCanon = pages.filter(f => {
  const m = /<link rel="canonical" href="([^"]+)">/.exec(read("c/" + f));
  return !m || m[1] !== `https://izzbah.com/c/${f}`;
});
check("…each canonicalises to its own live URL", wrongCanon.length === 0,
  wrongCanon.slice(0, 3).join(", "));
check("…and none still points into /preview/",
  !pages.some(f => read("c/" + f).includes("izzbah.com/preview")));

/* ── the sitemap is complete, and generated ─────────────────────── */
const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);
check("the sitemap lists the game", locs.includes("https://izzbah.com/"));
check("…the landing page", locs.includes("https://izzbah.com/about/"));
const missing = pages.filter(f => !locs.includes(`https://izzbah.com/c/${f}`));
check(`…and every category page (${pages.length})`, missing.length === 0,
  missing.slice(0, 3).join(", "));
/* ⚠️ NO REDIRECTS, ever. Listing `game-mobile.html` and `game.html` — stubs
   since the game moved to the root — is what invited "Page with redirect" in
   the first place. The /preview/ stubs are the same shape and must stay out. */
check("…and nothing that is a redirect stub",
  !locs.some(u => /game-mobile\.html|\/game\.html|\/preview\//.test(u)),
  locs.find(u => /game-mobile|\/game\.html|\/preview\//.test(u)) || "");
/* ⚠️ `legal.html` is noindex. Listing a page you have told Google to ignore is
   two contradictory instructions about the same URL. */
check("…and not the noindex policy page", !locs.some(u => /legal\.html/.test(u)));
// Hand-kept lists fall out of step the first time a category is published.
check("the sitemap is generated, not hand-written", /GENERATED by about\/cats\.mjs/.test(sitemap));
check("robots.txt points at it", /Sitemap:\s*https:\/\/izzbah\.com\/sitemap\.xml/.test(robots));
check("…and blocks nothing wholesale", !/^\s*Disallow:\s*\/\s*$/m.test(robots));
/* ⚠️ The repo IS the site: `.nojekyll` serves the branch raw, so every note file
   is readable at izzbah.com/<name>.md. This keeps them out of search results —
   it does NOT stop direct access, and must never be treated as a control. */
check("…but keeps the internal notes out of search", /Disallow:\s*\/\*\.md\$/.test(robots));
/* ⚠️ A PATTERN, never a list. robots.txt is public and is the first file a
   curious visitor opens, so naming a file here advertises the very thing it is
   meant to hide. This is the check that stops someone "improving" it later. */
check("…without naming a single one of them",
  !/Disallow:\s*\/[A-Za-z0-9_-]+\.md/.test(robots),
  (/Disallow:\s*\/[A-Za-z0-9_-]+\.md/.exec(robots) || [""])[0]);
// Deleted 2026-08-21: merchant-application material, served publicly, needed by nothing.
check("the Thawani onboarding pack is gone from the tree", !existsSync(join(ROOT, "THAWANI_ONBOARDING.md")));

/* ── the old addresses still resolve ────────────────────────────── */
for (const [what, f, dest] of [
  ["/preview/", "preview/index.html", "about/"],
  ["/preview/c/", "preview/c/index.html", "about/#all"],
]) {
  const stub = read(f);
  check(`${what} still resolves rather than 404ing`, stub.length > 0);
  check(`…forwarding to /${dest}`, stub.includes(dest));
  /* ⚠️ A redirect must be noindex itself, or Google files it as a page in its
     own right and reports it as one. */
  check(`…and is noindex, so it is never filed as a page`, /noindex/.test(stub));
}

const failed = checks.filter(x => !x).length;
console.log(failed ? `\n${failed} check(s) FAILED` : `\nall ${checks.length} checks passed`);
process.exit(failed ? 1 : 0);
