/* GENERATED by preview/sync.mjs — do not edit by hand.
   40 categories · 4748 questions, straight from Firestore. */
window.IZZBAH_DATA = {
 "totals": {
  "categories": 40,
  "questions": 4748,
  "omani": 9
 },
 "cats": [
  {
   "id": "pub-1783170084646-5700",
   "name": "جلسة حريم",
   "order": 11,
   "n": 100,
   "cover": "cat/pub-1783170084646-5700-t.webp",
   "big": "cat/pub-1783170084646-5700-l.webp",
   "om": 1
  },
  {
   "id": "pub-1783453062866-1028",
   "name": "حنكة عمانية",
   "order": 20,
   "n": 111,
   "cover": "cat/pub-1783453062866-1028-t.webp",
   "big": "cat/pub-1783453062866-1028-l.webp",
   "om": 1
  },
  {
   "id": "khareef",
   "name": "خريف ظفار",
   "order": -1,
   "n": 52,
   "cover": "../assets/img/cat-khareef.webp",
   "big": "../assets/img/cat-khareef.webp",
   "om": 1
  },
  {
   "id": "pub-1783425758108-102",
   "name": "رياكشنات عمانية",
   "order": 19,
   "n": 34,
   "cover": "cat/pub-1783425758108-102-t.webp",
   "big": "cat/pub-1783425758108-102-l.webp",
   "om": 1
  },
  {
   "id": "pub-1784798503561-5271",
   "name": "قديمك نديمك",
   "order": 35,
   "n": 89,
   "cover": "cat/pub-1784798503561-5271-t.webp",
   "big": "cat/pub-1784798503561-5271-l.webp",
   "om": 1
  },
  {
   "id": "cafesRestaurants",
   "name": "كافيهات ومطاعم",
   "order": -1,
   "n": 68,
   "cover": "cat/cafesRestaurants-t.webp",
   "big": "cat/cafesRestaurants-l.webp",
   "om": 1
  },
  {
   "id": "omaniFootball",
   "name": "كرة عمانية",
   "order": -1,
   "n": 44,
   "cover": "../assets/img/cat-omaniFootball.webp",
   "big": "../assets/img/cat-omaniFootball.webp",
   "om": 1
  },
  {
   "id": "pub-1783170059396-601",
   "name": "مواقع في عمان",
   "order": 10,
   "n": 195,
   "cover": "cat/pub-1783170059396-601-t.webp",
   "big": "cat/pub-1783170059396-601-l.webp",
   "om": 1
  },
  {
   "id": "pub-1783189569201-313",
   "name": "وش الكلمة (عماني)",
   "order": 18,
   "n": 94,
   "cover": "cat/pub-1783189569201-313-t.webp",
   "big": "cat/pub-1783189569201-313-l.webp",
   "om": 1
  },
  {
   "id": "arabicTerms",
   "name": "أحرف",
   "order": -1,
   "n": 99,
   "cover": "cat/arabicTerms-t.webp",
   "big": "cat/arabicTerms-l.webp",
   "nu": 1
  },
  {
   "id": "pub-1783684233589-5608",
   "name": "أعلام",
   "order": 29,
   "n": 132,
   "cover": "cat/pub-1783684233589-5608-t.webp",
   "big": "cat/pub-1783684233589-5608-l.webp"
  },
  {
   "id": "foreignMoviesOnly",
   "name": "أفلام أجنبية",
   "order": -1,
   "n": 134,
   "cover": "../assets/img/cat-foreignMoviesOnly.webp",
   "big": "../assets/img/cat-foreignMoviesOnly.webp"
  },
  {
   "id": "pub-1785323313470-2876",
   "name": "أكمل المثل",
   "order": 36,
   "n": 128,
   "cover": "cat/pub-1785323313470-2876-t.webp",
   "big": "cat/pub-1785323313470-2876-l.webp"
  },
  {
   "id": "pub-1784503983714-3987",
   "name": "الأقرب يفوز",
   "order": 33,
   "n": 100,
   "cover": "cat/pub-1784503983714-3987-t.webp",
   "big": "cat/pub-1784503983714-3987-l.webp"
  },
  {
   "id": "seerah",
   "name": "السيرة النبوية",
   "order": -1,
   "n": 130,
   "cover": "cat/seerah-t.webp",
   "big": "cat/seerah-l.webp"
  },
  {
   "id": "pub-1783510423551-6465",
   "name": "العاب",
   "order": 24,
   "n": 148,
   "cover": "cat/pub-1783510423551-6465-t.webp",
   "big": "cat/pub-1783510423551-6465-l.webp"
  },
  {
   "id": "pub-1784486305049-7855",
   "name": "ألغاز",
   "order": 32,
   "n": 80,
   "cover": "cat/pub-1784486305049-7855-t.webp",
   "big": "cat/pub-1784486305049-7855-l.webp"
  },
  {
   "id": "pub-1783170356019-2501",
   "name": "براندات",
   "order": 18,
   "n": 128,
   "cover": "cat/pub-1783170356019-2501-t.webp",
   "big": "cat/pub-1783170356019-2501-l.webp"
  },
  {
   "id": "history",
   "name": "تاريخ",
   "order": -1,
   "n": 140,
   "cover": "cat/history-t.webp",
   "big": "cat/history-l.webp"
  },
  {
   "id": "pub-1785819195566-4471",
   "name": "تطبيقات",
   "order": 39,
   "n": 57,
   "cover": "cat/pub-1785819195566-4471-t.webp",
   "big": "cat/pub-1785819195566-4471-l.webp"
  },
  {
   "id": "culture",
   "name": "ثقافة عامة",
   "order": -1,
   "n": 178,
   "cover": "cat/culture-t.webp",
   "big": "cat/culture-l.webp"
  },
  {
   "id": "geo",
   "name": "جغرافيا",
   "order": -1,
   "n": 132,
   "cover": "cat/geo-t.webp",
   "big": "cat/geo-l.webp"
  },
  {
   "id": "pub-1783170306877-1440",
   "name": "دين",
   "order": 14,
   "n": 5,
   "cover": "cat/pub-1783170306877-1440-t.webp",
   "big": "cat/pub-1783170306877-1440-l.webp"
  },
  {
   "id": "sports",
   "name": "رياضة",
   "order": -1,
   "n": 107,
   "cover": "cat/sports-t.webp",
   "big": "cat/sports-l.webp"
  },
  {
   "id": "cars",
   "name": "سيارات",
   "order": -1,
   "n": 141,
   "cover": "cat/cars-t.webp",
   "big": "cat/cars-l.webp"
  },
  {
   "id": "science",
   "name": "علوم",
   "order": -1,
   "n": 126,
   "cover": "cat/science-t.webp",
   "big": "cat/science-l.webp"
  },
  {
   "id": "sayAnother",
   "name": "قول غيرها",
   "order": -1,
   "n": 242,
   "cover": "cat/sayAnother-t.webp",
   "big": "cat/sayAnother-l.webp",
   "nu": 1
  },
  {
   "id": "foreignSeries",
   "name": "مسلسلات أجنبية",
   "order": -1,
   "n": 112,
   "cover": "cat/foreignSeries-t.webp",
   "big": "cat/foreignSeries-l.webp"
  },
  {
   "id": "pub-1783189666048-7547",
   "name": "مصارعة حره",
   "order": 19,
   "n": 56,
   "cover": "cat/pub-1783189666048-7547-t.webp",
   "big": "cat/pub-1783189666048-7547-l.webp"
  },
  {
   "id": "pub-1784240484235-8039",
   "name": "معنـى الايموجي",
   "order": 31,
   "n": 106,
   "cover": "cat/pub-1784240484235-8039-t.webp",
   "big": "cat/pub-1784240484235-8039-l.webp"
  },
  {
   "id": "emojis",
   "name": "معنى الايموجي (English)",
   "order": -1,
   "n": 120,
   "cover": "cat/emojis-t.webp",
   "big": "cat/emojis-l.webp"
  },
  {
   "id": "pub-1784043823835-6035",
   "name": "من الي سجل؟",
   "order": 29,
   "n": 31,
   "cover": "cat/pub-1784043823835-6035-t.webp",
   "big": "cat/pub-1784043823835-6035-l.webp"
  },
  {
   "id": "whoAmI",
   "name": "من أنا؟",
   "order": -1,
   "n": 116,
   "cover": "../assets/img/cat-whoAmI.webp",
   "big": "../assets/img/cat-whoAmI.webp"
  },
  {
   "id": "footballMix",
   "name": "منوعات كرة قدم",
   "order": -1,
   "n": 133,
   "cover": "cat/footballMix-t.webp",
   "big": "cat/footballMix-l.webp"
  },
  {
   "id": "pub-1783189684453-7350",
   "name": "ميمز",
   "order": 20,
   "n": 5,
   "cover": "cat/pub-1783189684453-7350-t.webp",
   "big": "cat/pub-1783189684453-7350-l.webp"
  },
  {
   "id": "pub-1784571861226-6942",
   "name": "وش الرابط؟",
   "order": 34,
   "n": 125,
   "cover": "cat/pub-1784571861226-6942-t.webp",
   "big": "cat/pub-1784571861226-6942-l.webp"
  },
  {
   "id": "charadesMovies",
   "name": "وش الكلمة أفلام",
   "order": -1,
   "n": 250,
   "cover": "cat/charadesMovies-t.webp",
   "big": "cat/charadesMovies-l.webp"
  },
  {
   "id": "charadesArabic",
   "name": "وش الكلمة عربي",
   "order": -1,
   "n": 250,
   "cover": "cat/charadesArabic-t.webp",
   "big": "cat/charadesArabic-l.webp"
  },
  {
   "id": "charadesSeries",
   "name": "وش الكلمة مسلسلات",
   "order": -1,
   "n": 200,
   "cover": "cat/charadesSeries-t.webp",
   "big": "cat/charadesSeries-l.webp"
  },
  {
   "id": "charades",
   "name": "وش كلمة أجنبي",
   "order": -1,
   "n": 250,
   "cover": "cat/charades-t.webp",
   "big": "cat/charades-l.webp"
  }
 ],
 "samples": [
  {
   "cat": "حنكة عمانية",
   "q": "متى بدأ حكم السيد سعيد بن تيمور؟(-سنتين+)",
   "a": "1932",
   "choices": [
    "1932",
    "1972",
    "1624",
    "2008"
   ],
   "points": 400
  },
  {
   "cat": "تاريخ",
   "q": "في أي قرن بدأت الثورة الصناعية؟",
   "a": "القرن الثامن عشر",
   "choices": [
    "القرن الثامن عشر",
    "القرن السابع عشر",
    "القرن التاسع عشر",
    "القرن السادس عشر"
   ],
   "points": 300
  },
  {
   "cat": "جغرافيا",
   "q": "ما أطول نهر في العالم؟",
   "a": "نهر النيل",
   "choices": [
    "نهر النيل",
    "نهر التيبر",
    "نهر الدانوب",
    "نهر السين"
   ],
   "points": 200
  },
  {
   "cat": "ثقافة عامة",
   "q": "كم عدد أيام السنة الكبيسة؟",
   "a": "366 يوم",
   "choices": [
    "366 يوم",
    "365 يوم",
    "367 يوم",
    "364 يوم"
   ],
   "points": 100
  },
  {
   "cat": "علوم",
   "q": "ما الغاز الذي تحتاجه النباتات لإتمام عملية البناء الضوئي؟",
   "a": "ثاني أكسيد الكربون",
   "choices": [
    "ثاني أكسيد الكربون",
    "الأكسجين",
    "النيتروجين",
    "الهيدروجين"
   ],
   "points": 100
  },
  {
   "cat": "سيارات",
   "q": "ما الشركة المصنعة لسيارة سوبرا؟",
   "a": "تويوتا",
   "choices": [
    "تويوتا",
    "نيسان",
    "هوندا",
    "مازدا"
   ],
   "points": 100
  }
 ]
};
