// Regenerates preview/data.js from the live game.
//
//   node preview/sync.mjs
//
// The landing page must never drift from the game. Everything factual on it —
// which categories exist, what they're called, how many questions each really
// has, the totals in the counters — comes from this file, and this file comes
// from Firestore. Rename a category in the admin panel, publish a new one, add
// questions: re-run this and the page follows.
//
// What stays hand-written in index.html is editorial only: each category's
// one-line description and its tag. Those are keyed by id, so a new category
// still appears (with a neutral fallback) until someone writes copy for it.
//
// Reads are public — firestore.rules has `allow read: if true` on /categories,
// which it must, because every player's browser reads the same data.
//
// Covers are NOT fetched here. They're base64 blobs inside the category docs
// (200-400 KB each, ~12 MB for all 39) and they change rarely, so resizing
// them is a separate deliberate step — see COVERS.md.

const KEY = "AIzaSyDRcH7DlI-CDRTKh0_a5svL9UutNRmIH2I"; // public web key, same one the game ships
const ROOT = "https://firestore.googleapis.com/v1/projects/izzbahgame/databases/(default)/documents";

// Categories with no cloud cover fall back to a bundled asset, exactly as the
// game does (see publishedCoverFallbacks in index.html).
const BUNDLED = {
  foreignMoviesOnly: "../assets/img/cat-foreignMoviesOnly.webp",
  khareef:           "../assets/img/cat-khareef.webp",
  omaniFootball:     "../assets/img/cat-omaniFootball.webp",
  whoAmI:            "../assets/img/cat-whoAmI.webp",
};
// Omani-only categories — the library's real differentiator, flagged on the grid.
const OMANI = new Set(["khareef","omaniFootball","cafesRestaurants",
  "pub-1783170059396-601","pub-1783189569201-313","pub-1783425758108-102",
  "pub-1783453062866-1028","pub-1784798503561-5271","pub-1783170084646-5700"]);
const NEW = new Set(["sayAnother","arabicTerms"]);

const get = async (url) => {
  for (let attempt = 1; ; attempt++) {
    try {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
      return await r.json();
    } catch (err) {
      if (attempt >= 4) throw err;
      await new Promise(r => setTimeout(r, 2 ** attempt * 1000));
    }
  }
};

// The category docs carry their cover inline, so ask only for the small fields
// or a single page balloons past the API's response limit.
async function categories() {
  const out = [];
  let token = null;
  do {
    const q = new URLSearchParams({ key: KEY, pageSize: "60" });
    ["name", "order"].forEach(f => q.append("mask.fieldPaths", f));
    if (token) q.set("pageToken", token);
    const d = await get(`${ROOT}/categories?${q}`);
    (d.documents || []).forEach(doc => {
      const f = doc.fields || {};
      const o = f.order || {};
      out.push({
        id: doc.name.split("/").pop(),
        name: (f.name && f.name.stringValue) || "",
        order: Number(o.integerValue ?? o.doubleValue ?? 0),
      });
    });
    token = d.nextPageToken;
  } while (token);
  return out;
}

// Counted from the questions subcollection rather than the doc's text-only
// copy, because that copy is capped and would under-report a large category.
async function countQuestions(id) {
  let n = 0, token = null;
  do {
    const q = new URLSearchParams({ key: KEY, pageSize: "300" });
    q.append("mask.fieldPaths", "idx");
    if (token) q.set("pageToken", token);
    const d = await get(`${ROOT}/categories/${encodeURIComponent(id)}/questions?${q}`);
    n += (d.documents || []).length;
    token = d.nextPageToken;
  } while (token);
  return n;
}

const cats = await categories();
if (!cats.length) { console.error("No categories came back — refusing to write an empty data.js."); process.exit(1); }

for (const c of cats) {
  c.n = await countQuestions(c.id);
  c.cover = BUNDLED[c.id] || `cat/${c.id}-t.webp`;
  c.big   = BUNDLED[c.id] || `cat/${c.id}-l.webp`;
  if (OMANI.has(c.id)) c.om = 1;
  if (NEW.has(c.id)) c.nu = 1;
  process.stderr.write(`  ${c.name.padEnd(26)} ${c.n}\n`);
}

// Omani first — they're the reason to choose عِزبة over any other trivia app —
// then the rest by name, so the order is stable between runs.
cats.sort((a, b) => (a.om ? 0 : 1) - (b.om ? 0 : 1) || a.name.localeCompare(b.name, "ar"));

const totals = {
  categories: cats.length,
  questions: cats.reduce((s, c) => s + c.n, 0),
  omani: cats.filter(c => c.om).length,
};

const { writeFileSync } = await import("fs");
const { fileURLToPath } = await import("url");
const { dirname, join } = await import("path");
const here = dirname(fileURLToPath(import.meta.url));

writeFileSync(join(here, "data.js"),
  "/* GENERATED by preview/sync.mjs — do not edit by hand.\n"
  + `   ${totals.categories} categories · ${totals.questions} questions, straight from Firestore. */\n`
  + "window.IZZBAH_DATA = " + JSON.stringify({ totals, cats }, null, 1) + ";\n", "utf8");

console.log(`\nwrote preview/data.js — ${totals.categories} categories, ${totals.questions} questions, ${totals.omani} Omani`);
const thin = cats.filter(c => c.n < 25);
if (thin.length) console.log("thin (under 25 questions):", thin.map(c => `${c.name} ${c.n}`).join(", "));
